post_upgrade() {
    if usr/bin/pacman-key -l >/dev/null 2>&1; then
        usr/bin/pacman-key --populate elseworld
    fi
}

post_install() {
    if [ -x usr/bin/pacman-key ]; then
        post_upgrade
    fi
}

post_remove() {
	if [[ -e "/usr/share/pacman/keyrings/elseworld.gpg" ]]; then
		rm -rf "/usr/share/pacman/keyrings/elseworld.gpg"
	fi
	if [[ -e "/usr/share/pacman/keyrings/elseworld-revoked" ]]; then
		rm -rf "/usr/share/pacman/keyrings/elseworld-revoked"
	fi
	if [[ -e "/usr/share/pacman/keyrings/elseworld-trusted" ]]; then
		rm -rf "/usr/share/pacman/keyrings/elseworld-trusted"
	fi
}
